name: Discoords
description: Discoords, allows to send the current coordinates to a discord channel
main: me.ricglz.discoords.Discoords
version: 0.1.2

commands:
    discoords:
      description: Send your current coordinates to your discord channel
      usage: /<command> <message>
    save-coords:
      description: Save your current coordinates to everyone to see it
      usage: /<command> <label>

permissions:
  discoords.*:
    description: Gives access to all discoords commands
    children:
      discoords.discoords: true
  discoords.discoords:
    description: Allows you to send your coordinates to discord
    default: true
