name: Discoords
description: Discoords, allows to send the current coordinates to a discord channel
main: me.ricglz.discoords.Discoords
version: 0.1.1

commands:
    discoords:
        description: Main command for discoords
        usage: /<command> [label]

permissions:
  discoords.*:
    description: Gives access to all discoords commands
    children:
      discoords.discoords: true
  discoords.discoords:
    description: Allows you to send your coordinates to discord
    default: true
